import { IDocumentList } from "../App/IDocument";
import { IClient } from "./iclient";
import { IClientContact } from "./iclientContactForm";
import { IClientsBankAccount } from "./iclientsBankAccountForm";

export interface IClientPreview extends IClient {
  sNo?: number;
  policyType?: string;
  officalName?: string;
  relationshipStatus?: string;
  oldClientID?: string;
  newClientID?: string;
  oldAccNoONB?: string;
  oldAccNoOFB?: string;
  prospID?: number;
  clientImportance?: string;
  registrationStatus?: string;
  businessActivity?: string;
  marketSegment?: string;
  location?: string;
  dateOfIncorporation?: Date;
  dateOfIncorporationHijri?: Date;
  placeOfIncorporation?: string;
  expiryDate?: Date;
  expiryDateHijri?: Date;
  coCountry?: string;
  registeredEntity?: string;
  email?: string;
  vatNo?: string;
  sponsorID?: string;
  nameOfExternal?: string;
  addressOfExternalAuditor?: string;
  tele?: string;
  tele2?: string;
  mobile?: string;
  fax?: string;
  poBox?: string;
  waselAddress?: string;
  claimsDeadline?: number;
  csDeadline?: number;
  website?: string;
  capital?: string;
  otherDetails?: string;
  buildingNo?: string;
  streetName?: string;
  districtName?: string;
  cityName?: string;
  zip?: string;
  additionalNo?: string;
  unitNo?: string;
  contactPersonName?: string;
  transDate?: Date;
  userName?: string;
  welcomeEmailSentFlag?: string;
  id?: string;
  idNo?: string;
  idExpiryDate?: Date;
  nationality?: string;
  sourceofIncome?: string;
  channel?: string;
  interface?: string;
  screeningResult?: string;
  premium?: string;
  updatedBy?: string;
  updatedOn?: Date;
  clientContactsArray?: string;
  clientsBankAccountsArray?: string;
  unifiedNo?: string;
  businessType?: string;
  notes?: string;
  insuranceCompany?: string;
  extension?: string;
  secondryNo?: string;
  postalCode?: string;
  documentLists?: IDocumentList[];
  clientContacts?: IClientContact[];
  clientsBankAccounts?: IClientsBankAccount[];

  documents2: any[];
}
