import { ClientContact } from "./iclientContactForm";
import { ClientsBankAccount } from "./iclientsBankAccountForm";

export interface iclientForms {
  status: string,
  policyType: string,
  fullName: string,
  fullNameAr: string,
  officalName: string,
  relationshipStatus: string,
  businessType: string,
  type: string,
  idNo: string,
  idExpiryDate: Date,
  nationality: string,
  sourceofIncome: string,
  registrationStatus: string,
  businessActivity: string,
  marketSegment: string,
  dateOfIncorporation: Date,
  dateOfIncorporationHijri: Date,
  commericalNo: string,
  expiryDate: Date,
  expiryDateHijri: Date,
  sponsorID: string,
  unifiedNo: string,
  vatNo: string,
  capital: string,
  location: string,
  premium: string,
  buildingNo: string,
  poBox: string,
  tele: string,
  tele2: string,
  fax: string,
  channel: string,
  interface: string,
  producer: string,
  screeningResult: string,
  branch: string,
  createdBy: string,
  streetName: string,
  secondryNo: string,
  districtName: string,
  postalCode: string,
  cityName: string,
  email: string,
  website: string,
  clientContacts: ClientContact[],
  clientsBankAccounts: ClientsBankAccount[],
  documents: string[],
}


