import { IDocumentList } from "../App/IDocument";

export interface ICustomerService {
	sno?: number | undefined;
	endorsType?: string | undefined;
	branch?: string | undefined;
	status?: string | undefined;
	endorsNo?: string | undefined;
	changeStatus?: string | undefined;
	docSno?: number | undefined;
	requestNo?: string | undefined;
	type?: string | undefined;
	requestStatusNote?: string | undefined;
	clientId?: number | undefined;
	prospectId?: number | undefined;
	clientName?: string | undefined;
	policyNo?: string | undefined;
	policySerial?: number | undefined;
	clientPolicySno?: number | undefined;
	insurComp?: string | undefined;
	classOfBusiness?: string | undefined;
	lineOfBusiness?: string | undefined;
	existingPolExpDate?: string | undefined;
	csspecialConditions?: string | undefined;
	requestDetails?: string | undefined;
	netPremium?: number | undefined;
	policyFees?: number | undefined;
	vatPerc?: number | undefined;
	vatValue?: number | undefined;
	vatAmount?: number | undefined;
	totalPremium?: number | undefined;
	savedBy?: string | undefined;
	savedDate?: Date | undefined;
	updatedBy?: string | undefined;
	updatedOn?: Date | undefined;
	closedBy?: string | undefined;
	closedOn?: Date | undefined;
	cancelationReason?: string | undefined;
	canceledBy?: string | undefined;
	canceledOn?: Date | undefined;
	finVerified?: number | undefined;
	dateOfReminder?: Date | undefined;
	dateOfDeadline?: Date | undefined;
	notifyClient?: number | undefined;
	notifyInsurer?: number | undefined;
	producer?: string | undefined;
	number?: string | undefined;
	email?: string | undefined;
	rejectionReason?: string | undefined;
	documentLists?: IDocumentList[];
	documentsModel?: IDocumentList[];
	requiermentsList?: any[];
}
