import { FormControl } from "@angular/forms";

export interface IUserRolesPrivilegesForm {
	sNo?: FormControl<number | null>;
	viewAllBranchs?: FormControl<boolean | null>;
	chAccessAllProducers?: FormControl<boolean | null>;
	chClientsRegistryAdmin?: FormControl<boolean | null>;
	chProduction?: FormControl<boolean | null>;
	chInsurClass?: FormControl<boolean | null>;
	chProdRetail?: FormControl<boolean | null>;
	chMasterInsClassesLines?: FormControl<boolean | null>;
	chMasterInsCompanies?: FormControl<boolean | null>;
	chBussDevProspects?: FormControl<boolean | null>;
	chFixedAssets?: FormControl<boolean | null>;
	chCustomerService?: FormControl<boolean | null>;
	chAccessAllUsersCSRequests?: FormControl<boolean | null>;
	chCustSerReports?: FormControl<boolean | null>;
	chCustSerRequests?: FormControl<boolean | null>;
	chBussDevUnderwritingMedical?: FormControl<boolean | null>;
	chBussDevUnderwriting?: FormControl<boolean | null>;
	chBussDevSales?: FormControl<boolean | null>;
	chBussDevelopment?: FormControl<boolean | null>;
	chAccessAllUsersSalesLeads?: FormControl<boolean | null>;
	chMasterTablesReadOnly?: FormControl<boolean | null>;
	chMasterProductionLibararies?: FormControl<boolean | null>;
	chMasterClaimsModule?: FormControl<boolean | null>;
	chMasterDefaultEmails?: FormControl<boolean | null>;
	chMasterCustServiceModule?: FormControl<boolean | null>;
	chMasterInsBrokers?: FormControl<boolean | null>;
	chBusinessDevelopmentReadOnly?: FormControl<boolean | null>;
	chClientsRegistryAdministratorReadOnly?: FormControl<boolean | null>;
	chProdCommercial?: FormControl<boolean | null>;
	chProdEntryApproval?: FormControl<boolean | null>;
	chApprovClientCreation?: FormControl<boolean | null>;
	chProdFinancialApprove?: FormControl<boolean | null>;
	chUpdateDeliveryStatus?: FormControl<boolean | null>;
	chProdIndividual?: FormControl<boolean | null>;
	chMasterTabels?: FormControl<boolean | null>;
	chProdPolicies?: FormControl<boolean | null>;
	chEntryCorrection?: FormControl<boolean | null>;
	chSearchEngine?: FormControl<boolean | null>;
	chProdReports?: FormControl<boolean | null>;
	chShowComanyCommission?: FormControl<boolean | null>;
	chShowProducerCommission?: FormControl<boolean | null>;
	chChangeProducerComm?: FormControl<boolean | null>;
	chAccessAllProducersSales?: FormControl<boolean | null>;
	chAccessAllProducersClients?: FormControl<boolean | null>;
	chAccessAllProducersProduction?: FormControl<boolean | null>;
	chProdTargets?: FormControl<boolean | null>;
	chProductionReadOnly?: FormControl<boolean | null>;
	chSales?: FormControl<boolean | null>;
	chSlipMng?: FormControl<boolean | null>;
	chProspReAssign?: FormControl<boolean | null>;
	chProspMangFollowUp?: FormControl<boolean | null>;
	chProspReport?: FormControl<boolean | null>;
	chRenewAssign?: FormControl<boolean | null>;
	chRenewMangFollowUp?: FormControl<boolean | null>;
	chRenewReport?: FormControl<boolean | null>;
	chClaims?: FormControl<boolean | null>;
	chClaimsDelManger?: FormControl<boolean | null>;
	chClaimsDelCorrec?: FormControl<boolean | null>;
	chClaimsManagement?: FormControl<boolean | null>;
	chClaimsMng?: FormControl<boolean | null>;
	chClaimsPaymentApproval?: FormControl<boolean | null>;
	chClaimsConfirmCN?: FormControl<boolean | null>;
	chClaimsReport?: FormControl<boolean | null>;
	chClaimsReports?: FormControl<boolean | null>;
	chReActivateClaims?: FormControl<boolean | null>;
	chClaimsFollowup?: FormControl<boolean | null>;
	reports?: FormControl<boolean | null>;
	chUnderwriting?: FormControl<boolean | null>;
	chUnderRequests?: FormControl<boolean | null>;
	chFinance?: FormControl<boolean | null>;
	chFinReports?: FormControl<boolean | null>;
	chFinMakeNew?: FormControl<boolean | null>;
	chFinMakeJV?: FormControl<boolean | null>;
	chFinMakeReceipt?: FormControl<boolean | null>;
	chFinMakePay?: FormControl<boolean | null>;
	chFinMakeReverse?: FormControl<boolean | null>;
	chFinReviewJV?: FormControl<boolean | null>;
	chFinReviewReceipt?: FormControl<boolean | null>;
	chFinancialManager?: FormControl<boolean | null>;
	chFinReviewPay?: FormControl<boolean | null>;
	chFinArchive?: FormControl<boolean | null>;
	chFinPayApprovals?: FormControl<boolean | null>;
	chFinReceiptApprovals?: FormControl<boolean | null>;
	chClaimsApproval?: FormControl<boolean | null>;
	chFinApprovals?: FormControl<boolean | null>;
	chFinDNsArchive?: FormControl<boolean | null>;
	chFinCNsArchive?: FormControl<boolean | null>;
	chFinReceiptArchive?: FormControl<boolean | null>;
	chFinPayArchive?: FormControl<boolean | null>;
	chFinanceEntryApproval?: FormControl<boolean | null>;
	chFinanceRenameAccounts?: FormControl<boolean | null>;
	chStatementOfAccount?: FormControl<boolean | null>;
	chTrialBalance?: FormControl<boolean | null>;
	chDataLock?: FormControl<boolean | null>;
	chFinSettings?: FormControl<boolean | null>;
	chFinDisableAccounts?: FormControl<boolean | null>;
	chProftAndLoss?: FormControl<boolean | null>;
	chSystemAdmin?: FormControl<boolean | null>;
	chUsersMang?: FormControl<boolean | null>;
	chSMSControlPanel?: FormControl<boolean | null>;
	chEmailsLog?: FormControl<boolean | null>;
	chClientsRegistry?: FormControl<boolean | null>;
	chClientsGrouping?: FormControl<boolean | null>;
	cHduePayments?: FormControl<boolean | null>;
	chExpiredPolices?: FormControl<boolean | null>;
	chPandingSalesLead?: FormControl<boolean | null>;
	chClientsApproval?: FormControl<boolean | null>;
	chVacApprovalDeptManager?: FormControl<boolean | null>;
	chApprovalDeptManager?: FormControl<boolean | null>;
	chCLaimManagerAppr?: FormControl<boolean | null>;
	chExpiredLeadsPolices?: FormControl<boolean | null>;
	chApproval?: FormControl<boolean | null>;
	chCloseFinancialYear?: FormControl<boolean | null>;
	alert?: FormControl<boolean | null>;
	productionCombExpApprove?: FormControl<boolean | null>;
	leadCurrentPolicies?: FormControl<boolean | null>;
	stampedPolicy?: FormControl<boolean | null>;
	chAuditAndReview?: FormControl<boolean | null>;
	chProducersPaymnets?: FormControl<boolean | null>;
	chClientsPaymentsManager?: FormControl<boolean | null>;
	chIncuranceClasses?: FormControl<boolean | null>;
	chInsuranceCompanies?: FormControl<boolean | null>;
	chInsuranceBrokers?: FormControl<boolean | null>;
	chProducers?: FormControl<boolean | null>;
	chAccountManager?: FormControl<boolean | null>;
	chAccessAllClients?: FormControl<boolean | null>;
	chTypeProspects?: FormControl<boolean | null>;
	chBusinessActivity?: FormControl<boolean | null>;
	chClientsCategories?: FormControl<boolean | null>;
	chCustomerServiceModule?: FormControl<boolean | null>;
	chProductionBusinessModules?: FormControl<boolean | null>;
	chUpdateClientDNCNCompCNDN?: FormControl<boolean | null>;
	chClaimsModule?: FormControl<boolean | null>;
	chListOfRequiredDocuments?: FormControl<boolean | null>;
	chContactsListPosition?: FormControl<boolean | null>;
	chCountries?: FormControl<boolean | null>;
	chDefaultEmails?: FormControl<boolean | null>;
	chProspectRegistry?: FormControl<boolean | null>;
	chSalesManagement?: FormControl<boolean | null>;
	chUnderwritingDepartment?: FormControl<boolean | null>;
	chBussUnderwritingMedical?: FormControl<boolean | null>;
	chBussUnderwritingGeneral?: FormControl<boolean | null>;
	chBusinessReports?: FormControl<boolean | null>;
	chRequestsManagements?: FormControl<boolean | null>;
	chClosingPeriod?: FormControl<boolean | null>;
	chNewReverseVoucher?: FormControl<boolean | null>;
	chEditingCorrecting?: FormControl<boolean | null>;
	chEditJournalVouchers?: FormControl<boolean | null>;
	chEditReceiptVoucher?: FormControl<boolean | null>;
	chEditPayVouchers?: FormControl<boolean | null>;
	chManageChartofAccounts?: FormControl<boolean | null>;
	chRenameAnAccount?: FormControl<boolean | null>;
	chDifferentInExchange?: FormControl<boolean | null>;
	chAllocationClearing?: FormControl<boolean | null>;
	chApproveInsuranceCompany?: FormControl<boolean | null>;
	chApprovingFinVouchersJV?: FormControl<boolean | null>;
	chApprovingFinVouchersRV?: FormControl<boolean | null>;
	chApprovingFinVouchersPV?: FormControl<boolean | null>;
	chApprovingFinVouchersReverse?: FormControl<boolean | null>;
	chHR?: FormControl<boolean | null>;
	chStaffProfiles?: FormControl<boolean | null>;
	chStaffContracts?: FormControl<boolean | null>;
	chAirTickets?: FormControl<boolean | null>;
	chGovernmentExpenses?: FormControl<boolean | null>;
	chHealthInsurance?: FormControl<boolean | null>;
	chLegalLicenseAndOfficialServices?: FormControl<boolean | null>;
	chIncidents?: FormControl<boolean | null>;
	chJobsOffersManagement?: FormControl<boolean | null>;
	chVacationsManagement?: FormControl<boolean | null>;
	chLoansManagement?: FormControl<boolean | null>;
	chOvertime?: FormControl<boolean | null>;
	chDeductibles?: FormControl<boolean | null>;
	chPayroll?: FormControl<boolean | null>;
	chAppraisalForm?: FormControl<boolean | null>;
	chReports?: FormControl<boolean | null>;
	chSettings?: FormControl<boolean | null>;
	chHRDeleteApprovedEntries?: FormControl<boolean | null>;
	chDepartmentVacations?: FormControl<boolean | null>;
	chVacationsRequest?: FormControl<boolean | null>;
	chhrAlarms?: FormControl<boolean | null>;
	chSalesforceSupport?: FormControl<boolean | null>;
	chAlertExpiringLegal?: FormControl<boolean | null>;
	chAlertExpiringVisa?: FormControl<boolean | null>;
	chAlertExpiringPassport?: FormControl<boolean | null>;
	chAlertExpiringID?: FormControl<boolean | null>;
	chAlertExpiringLabours?: FormControl<boolean | null>;
	chAlertExpiringContracts?: FormControl<boolean | null>;
	chAccessAllUsersSales?: FormControl<boolean | null>;
	chProductionEntryApproval?: FormControl<boolean | null>;
	chDeleteFollowUp?: FormControl<boolean | null>;
	chPReactivated?: FormControl<boolean | null>;
	chAccessAllBranchBussiness?: FormControl<boolean | null>;
	chAccessAllBrancheCustomer?: FormControl<boolean | null>;
	chAccessAllUsersCustomer?: FormControl<boolean | null>;
	chAccessAllBrancheClaim?: FormControl<boolean | null>;
	chAccessAllUsersClaim?: FormControl<boolean | null>;
	chProductionAccessAllUsers?: FormControl<boolean | null>;
	chAccessConfidentialAccounts?: FormControl<boolean | null>;
	chAccessAllBrancheFin?: FormControl<boolean | null>;
	chCustomerServiceReadOnly?: FormControl<boolean | null>;
	chClaimsManagementSystemReadOnly?: FormControl<boolean | null>;
	chFinancialManagementSystemReadOnly?: FormControl<boolean | null>;
	chHRReadOnly?: FormControl<boolean | null>;
	chSystemAdminReadOnly?: FormControl<boolean | null>;
	chRenameStaffName?: FormControl<boolean | null>;
	chFixedAssetsReadOnly?: FormControl<boolean | null>;
	chHideCompanyCommission?: FormControl<boolean | null>;
	chHideProducerCommission?: FormControl<boolean | null>;
	chModifyCommOut?: FormControl<boolean | null>;
	chHoldSalary?: FormControl<boolean | null>;
	chPayrollArchive?: FormControl<boolean | null>;
	chSchoolAllowanceManagement?: FormControl<boolean | null>;
	chMobileAllowances?: FormControl<boolean | null>;
	chActivatePayroll?: FormControl<boolean | null>;
	chGeneratePayroll?: FormControl<boolean | null>;
	chBonusManagement?: FormControl<boolean | null>;
	chRetroactiveManagement?: FormControl<boolean | null>;
	chSalaryandBenefits?: FormControl<boolean | null>;
	chLetterWarning?: FormControl<boolean | null>;
	chLetterEmbassy?: FormControl<boolean | null>;
	chLetterEndofService?: FormControl<boolean | null>;
	chLetterEffectiveDateNotice?: FormControl<boolean | null>;
	chLetterEmployment?: FormControl<boolean | null>;
	chLetterSalaryTransfer?: FormControl<boolean | null>;
	chLetterSalaryDefinition?: FormControl<boolean | null>;
	chLetterReleaseandDischargeForm?: FormControl<boolean | null>;
	chLetterJoiningLetters?: FormControl<boolean | null>;
	chLetterSponsorshipTransfer?: FormControl<boolean | null>;
	chLetterTemporaryProfile?: FormControl<boolean | null>;
	chLetterFieldApplication?: FormControl<boolean | null>;
	chLetterAuthorization?: FormControl<boolean | null>;
	chEndofService?: FormControl<boolean | null>;
	chCSEntryCorrection?: FormControl<boolean | null>;
	chComplaintsRegistry?: FormControl<boolean | null>;
	chOnlineRequests?: FormControl<boolean | null>;
	chLetters?: FormControl<boolean | null>;
	chAlertVacationRequest?: FormControl<boolean | null>;
	chAlertLeaveRequest?: FormControl<boolean | null>;
	chAlertRemindinglegal?: FormControl<boolean | null>;
	chAlertExpiringProbation?: FormControl<boolean | null>;
	chAlertDueContracts?: FormControl<boolean | null>;
	chAlertCustomerServiceDeadline?: FormControl<boolean | null>;
	chAlertClaimReminder?: FormControl<boolean | null>;
	chEnabledStatusRequst?: FormControl<boolean | null>;
	chAccessAllUsers?: FormControl<boolean | null>;
}

export interface IUserRolesPrivileges {
	sNo: number;
	viewAllBranchs: number;
	chAccessAllProducers: number;
	chClientsRegistryAdmin: number;
	chProduction: number;
	chInsurClass: number;
	chProdRetail: number;
	chMasterInsClassesLines: number;
	chMasterInsCompanies: number;
	chBussDevProspects: number;
	chFixedAssets: number;
	chCustomerService: number;
	chAccessAllUsersCSRequests: number;
	chCustSerReports: number;
	chCustSerRequests: number;
	chBussDevUnderwritingMedical: number;
	chBussDevUnderwriting: number;
	chBussDevSales: number;
	chBussDevelopment: number;
	chAccessAllUsersSalesLeads: number;
	chMasterTablesReadOnly: number;
	chMasterProductionLibararies: number;
	chMasterClaimsModule: number;
	chMasterDefaultEmails: number;
	chMasterCustServiceModule: number;
	chMasterInsBrokers: number;
	chBusinessDevelopmentReadOnly: number;
	chClientsRegistryAdministratorReadOnly: number;
	chProdCommercial: number;
	chProdEntryApproval: number;
	chApprovClientCreation: number;
	chProdFinancialApprove: number;
	chUpdateDeliveryStatus: number;
	chProdIndividual: number;
	chMasterTabels: number;
	chProdPolicies: number;
	chEntryCorrection: number;
	chSearchEngine: number;
	chProdReports: number;
	chShowComanyCommission: number;
	chShowProducerCommission: number;
	chChangeProducerComm: number;
	chAccessAllProducersSales: number;
	chAccessAllProducersClients: number;
	chAccessAllProducersProduction: number;
	chProdTargets: number;
	chProductionReadOnly: number;
	chSales: number;
	chSlipMng: number;
	chProspReAssign: number;
	chProspMangFollowUp: number;
	chProspReport: number;
	chRenewAssign: number;
	chRenewMangFollowUp: number;
	chRenewReport: number;
	chClaims: number;
	chClaimsDelManger: number;
	chClaimsDelCorrec: number;
	chClaimsManagement: number;
	chClaimsMng: number;
	chClaimsPaymentApproval: number;
	chClaimsConfirmCN: number;
	chClaimsReport: number;
	chClaimsReports: number;
	chReActivateClaims: number;
	chClaimsFollowup: number;
	reports: number;
	chUnderwriting: number;
	chUnderRequests: number;
	chFinance: number;
	chFinReports: number;
	chFinMakeNew: number;
	chFinMakeJV: number;
	chFinMakeReceipt: number;
	chFinMakePay: number;
	chFinMakeReverse: number;
	chFinReviewJV: number;
	chFinReviewReceipt: number;
	chFinancialManager: number;
	chFinReviewPay: number;
	chFinArchive: number;
	chFinPayApprovals: number;
	chFinReceiptApprovals: number;
	chClaimsApproval: number;
	chFinApprovals: number;
	chFinDNsArchive: number;
	chFinCNsArchive: number;
	chFinReceiptArchive: number;
	chFinPayArchive: number;
	chFinanceEntryApproval: number;
	chFinanceRenameAccounts: number;
	chStatementOfAccount: number;
	chTrialBalance: number;
	chDataLock: number;
	chFinSettings: number;
	chFinDisableAccounts: number;
	chProftAndLoss: number;
	chSystemAdmin: number;
	chUsersMang: number;
	chSMSControlPanel: number;
	chEmailsLog: number;
	chClientsRegistry: number;
	chClientsGrouping: number;
	cHduePayments: number;
	chExpiredPolices: number;
	chPandingSalesLead: number;
	chClientsApproval: number;
	chVacApprovalDeptManager: number;
	chApprovalDeptManager: number;
	chCLaimManagerAppr: number;
	chExpiredLeadsPolices: number;
	chApproval: number;
	chCloseFinancialYear: number;
	alert: number;
	productionCombExpApprove: number;
	leadCurrentPolicies: number;
	stampedPolicy: number;
	chAuditAndReview: number;
	chProducersPaymnets: number;
	chClientsPaymentsManager: number;
	chIncuranceClasses: number;
	chInsuranceCompanies: number;
	chInsuranceBrokers: number;
	chProducers: number;
	chAccountManager: number;
	chAccessAllClients: number;
	chTypeProspects: number;
	chBusinessActivity: number;
	chClientsCategories: number;
	chCustomerServiceModule: number;
	chProductionBusinessModules: number;
	chUpdateClientDNCNCompCNDN: number;
	chClaimsModule: number;
	chListOfRequiredDocuments: number;
	chContactsListPosition: number;
	chCountries: number;
	chDefaultEmails: number;
	chProspectRegistry: number;
	chSalesManagement: number;
	chUnderwritingDepartment: number;
	chBussUnderwritingMedical: number;
	chBussUnderwritingGeneral: number;
	chBusinessReports: number;
	chRequestsManagements: number;
	chClosingPeriod: number;
	chNewReverseVoucher: number;
	chEditingCorrecting: number;
	chEditJournalVouchers: number;
	chEditReceiptVoucher: number;
	chEditPayVouchers: number;
	chManageChartofAccounts: number;
	chRenameAnAccount: number;
	chDifferentInExchange: number;
	chAllocationClearing: number;
	chApproveInsuranceCompany: number;
	chApprovingFinVouchersJV: number;
	chApprovingFinVouchersRV: number;
	chApprovingFinVouchersPV: number;
	chApprovingFinVouchersReverse: number;
	chHR: number;
	chStaffProfiles: number;
	chStaffContracts: number;
	chAirTickets: number;
	chGovernmentExpenses: number;
	chHealthInsurance: number;
	chLegalLicenseAndOfficialServices: number;
	chIncidents: number;
	chJobsOffersManagement: number;
	chVacationsManagement: number;
	chLoansManagement: number;
	chOvertime: number;
	chDeductibles: number;
	chPayroll: number;
	chAppraisalForm: number;
	chReports: number;
	chSettings: number;
	chHRDeleteApprovedEntries: number;
	chDepartmentVacations: number;
	chVacationsRequest: number;
	chhrAlarms: number;
	chSalesforceSupport: number;
	chAlertExpiringLegal: number;
	chAlertExpiringVisa: number;
	chAlertExpiringPassport: number;
	chAlertExpiringID: number;
	chAlertExpiringLabours: number;
	chAlertExpiringContracts: number;
	chAccessAllUsersSales: number;
	chProductionEntryApproval: number;
	chDeleteFollowUp: number;
	chPReactivated: number;
	chAccessAllBranchBussiness: number;
	chAccessAllBrancheCustomer: number;
	chAccessAllUsersCustomer: number;
	chAccessAllBrancheClaim: number;
	chAccessAllUsersClaim: number;
	chProductionAccessAllUsers: number;
	chAccessConfidentialAccounts: number;
	chAccessAllBrancheFin: number;
	chCustomerServiceReadOnly: number;
	chClaimsManagementSystemReadOnly: number;
	chFinancialManagementSystemReadOnly: number;
	chHRReadOnly: number;
	chSystemAdminReadOnly: number;
	chRenameStaffName: number;
	chFixedAssetsReadOnly: number;
	chHideCompanyCommission: number;
	chHideProducerCommission: number;
	chModifyCommOut: number;
	chHoldSalary: number;
	chPayrollArchive: number;
	chSchoolAllowanceManagement: number;
	chMobileAllowances: number;
	chActivatePayroll: number;
	chGeneratePayroll: number;
	chBonusManagement: number;
	chRetroactiveManagement: number;
	chSalaryandBenefits: number;
	chLetterWarning: number;
	chLetterEmbassy: number;
	chLetterEndofService: number;
	chLetterEffectiveDateNotice: number;
	chLetterEmployment: number;
	chLetterSalaryTransfer: number;
	chLetterSalaryDefinition: number;
	chLetterReleaseandDischargeForm: number;
	chLetterJoiningLetters: number;
	chLetterSponsorshipTransfer: number;
	chLetterTemporaryProfile: number;
	chLetterFieldApplication: number;
	chLetterAuthorization: number;
	chEndofService: number;
	chCSEntryCorrection: number;
	chComplaintsRegistry: number;
	chOnlineRequests: number;
	chLetters: number;
	chAlertVacationRequest: number;
	chAlertLeaveRequest: number;
	chAlertRemindinglegal: number;
	chAlertExpiringProbation: number;
	chAlertDueContracts: number;
	chAlertCustomerServiceDeadline: number;
	chAlertClaimReminder: number;
	chEnabledStatusRequst: number;
	chAccessAllUsers: number;
}
