export interface ISystemAdmin
{
    sno?: number,
    userName?: string,
    fullName?: string,
    producer?: string,
    staffId?: number,
    jobTitle?: string,
    phoneNo?: string,
    email?: string,
    emailPassword?: string,
    branch?: string,
    status?: string,
    pass?: string,
    oldPassword?: any,
    savedUser?: string,
    savedDate?: Date,
    updateUser?: string,
    updateDate?: Date,
    passwordChangeDate?: Date,
    costCentersDepartment?: string,
    costCentersDivision?: string,
    lastLogin?: string,
    userRole?: string,
    identity?: string;
}